name: Build and Deploy

on:
  push:
    branches:
      - master
      - pages-*

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: "true"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Jekyll and plugins
        run: |
          gem install jekyll -v 4.4.1
          gem install kramdown-parser-gfm jekyll-sitemap jekyll-feed jekyll-paginate-v2 jekyll-menus jekyll-analytics jekyll-seo-tag

      - name: Build site
        run: JEKYLL_ENV=production jekyll build --destination ./_site

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4
